SET IDENTITY_INSERT Tasks ON
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (1, 'Fintone', 'Other family member, perpetrator of maltreatment and neglect', '1/5/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (2, 'Fixflex', 'Dislocation of unsp acromioclav jt, > 200% displacmnt', '2/22/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (3, 'Tin', 'Unsp injury at unsp level of cervical spinal cord, sequela', '7/9/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (4, 'Y-Solowarm', 'Burn of mouth and pharynx, initial encounter', '3/14/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (5, 'Flexidy', 'Infection oth prt genital tract in pregnancy, unsp trimester', '4/7/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (6, 'Sonsing', 'Laceration with foreign body of right ear, initial encounter', '2/28/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (7, 'Cookley', 'Open bite, left foot, subsequent encounter', '6/14/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (8, 'Biodex', 'Displaced fracture of posterior column of left acetabulum', '6/23/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (9, 'Domainer', 'Corrosion of unsp degree of female genital region, init', '6/5/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (10, 'Zathin', 'Congenital dislocation of hip, bilateral', '9/27/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (11, 'Bitwolf', 'Insect bite (nonvenomous), unspecified hip, sequela', '1/20/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (12, 'Matsoft', 'Person injured in clsn betw mtr veh and 2/3-whl mv, subs', '4/22/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (13, 'Zaam-Dox', 'Loose body in left finger joint(s)', '8/6/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (14, 'Sub-Ex', 'Salter-Harris Type III physeal fracture of r calcaneus, 7thB', '4/25/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (15, 'Sub-Ex', 'Nondisp pilon fx r tibia, 7thM', '12/3/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (16, 'Hatity', 'Oth osteopor w crnt path fx, unsp humer, 7thG', '4/23/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (17, 'Bitchip', 'Displ transverse fx shaft of r tibia, 7thN', '5/17/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (18, 'Greenlam', 'Burn of second degree of unspecified axilla, init encntr', '9/15/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (19, 'Tin', 'Sltr-haris Type III physl fx upr end rad, l arm, 7thD', '6/14/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (20, 'Subin', 'Unsp traum displ spondylolysis of 5th cervcal vert, 7thG', '1/24/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (21, 'Holdlamis', 'Coronary angioplasty status', '10/10/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (22, 'Stim', 'Contusion of left hand, subsequent encounter', '7/11/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (23, 'Cardguard', 'Burn second degree of single l finger except thumb, init', '4/29/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (24, 'Ronstring', 'Sprain of interphalangeal joint of left little finger', '5/25/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (25, 'Tres-Zap', 'NIHSS score 26', '3/1/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (26, 'Tin', '22 weeks gestation of pregnancy', '12/8/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (27, 'Tempsoft', 'Dvrtclos of lg int w/o perforation or abscess w bleeding', '8/25/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (28, 'Fintone', 'Cholesteatoma of attic, right ear', '11/2/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (29, 'Biodex', 'Unspecified injury of unspecified hip, subsequent encounter', '8/14/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (30, 'Cardguard', 'Unsp comp of fb acc left in body following punctr/cath, init', '3/19/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (31, 'Duobam', 'Personal history of malignant neoplasm of endocrine glands', '10/25/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (32, 'Y-find', 'Unsp fx low end unsp tibia, 7thF', '9/13/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (33, 'Voyatouch', 'Inhalant dependence with inhalant-induced anxiety disorder', '9/21/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (34, 'Gembucket', 'Displ unsp condyle fx low end l femr, 7thF', '4/30/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (35, 'Konklux', 'Disp fx of less tuberosity of unsp humer, 7thP', '3/18/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (36, 'Lotstring', 'Corrosion of first degree of unspecified ear', '8/3/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (37, 'Andalax', 'Disp fx of dist pole of navic bone of r wrs, 7thG', '6/13/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (38, 'Zontrax', 'Abrasion of unspecified front wall of thorax, subs encntr', '12/19/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (39, 'Vagram', 'Pnctr w/o foreign body of l little finger w damage to nail', '3/27/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (40, 'Cookley', 'Toxic effect of glycols, assault', '6/7/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (41, 'Matsoft', 'Osteonecrosis due to drugs, left foot', '9/30/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (42, 'Solarbreeze', 'Lac w fb of r frnt wl of thorax w penet thor cavity, sequela', '2/27/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (43, 'Redhold', 'Poisoning by oxytocic drugs, accidental (unintentional)', '12/1/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (44, 'Namfix', 'Displaced fracture of shaft of right clavicle', '2/17/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (45, 'Cardguard', 'Other reactive arthropathies, knee', '3/25/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (46, 'Treeflex', 'Displ apophyseal fx r femur, subs for clos fx w routn heal', '10/10/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (47, 'Stim', 'Sltr-haris Type I physeal fx unspecified metatarsal, 7thG', '12/29/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (48, 'Cookley', 'Tuberculosis of kidney and ureter', '5/19/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (49, 'Tampflex', 'Partial traumatic amputation at unsp shoulder joint, sequela', '4/17/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (50, 'Stronghold', 'Relapsing fevers', '11/28/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (51, 'Tin', 'Poisoning by oth viral vaccines, accidental, init', '11/20/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (52, 'Tempsoft', 'Cont preg aft spon abort of one fts or more, unsp tri, fts5', '7/27/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (53, 'Subin', 'Prsnl hx of congen malform of integument, limbs and ms sys', '2/10/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (54, 'Stringtough', 'Circadian rhythm sleep disorder, shift work type', '5/1/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (55, 'Tres-Zap', 'Osteochondral fracture of patella', '7/8/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (56, 'Kanlam', 'Oth disrd of the skin, subcu related to radiation', '1/29/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (57, 'Tin', 'Nondisp dome fx left talus, subs for fx w routn heal', '11/26/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (58, 'Gembucket', 'Dieulafoy lesion of intestine', '8/5/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (59, 'Fintone', 'Malignant neoplasm of pylorus', '5/27/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (60, 'Zamit', 'Displacement of implanted urinary sphincter', '6/9/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (61, 'Zathin', 'Abrasion, unspecified lower leg', '6/18/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (62, 'Duobam', 'Stable burst fracture of fifth lumbar vertebra', '1/22/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (63, 'Stringtough', 'Multiple fractures of pelvis with disruption of pelvic ring', '2/13/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (64, 'Alpha', 'Fracture of unsp phalanx of l mid finger, init for opn fx', '4/7/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (65, 'Tresom', 'Underdosing of methadone, sequela', '5/12/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (66, 'Bamity', 'Unsp fx lower end of r femur, subs for clos fx w routn heal', '2/5/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (67, 'Home Ing', 'Burn of second degree of left thumb (nail), subs encntr', '12/29/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (68, 'Aerified', 'Other subluxation of right wrist and hand, sequela', '2/12/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (69, 'Biodex', 'Underdosing of other synthetic narcotics, initial encounter', '10/8/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (70, 'Job', 'Oth specific joint derangements of right hand, NEC', '4/21/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (71, 'Cardguard', 'Cerebral venous thrombosis in pregnancy, unsp trimester', '4/22/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (72, 'Lotstring', 'Underdosing of therapeutic gases', '3/16/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (73, 'Zathin', 'Lacerat blood vessels at lower leg level, right leg, init', '12/5/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (74, 'Mat Lam Tam', 'Activity, roller coaster riding', '1/3/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (75, 'Rank', 'Charcot''s joint, left wrist', '10/25/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (76, 'Solarbreeze', 'Sprain of other part of wrist and hand', '3/11/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (77, 'Tin', 'Bicipital tendinitis, unspecified shoulder', '1/18/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (78, 'Bitwolf', 'Partial traumatic amp of unsp foot at ankle level, subs', '9/27/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (79, 'Ventosanzap', 'Maternal care for fetal abnlt and damage, unsp, fetus 1', '2/1/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (80, 'Y-Solowarm', 'Acquired keratosis follicularis', '1/6/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (81, 'Job', 'Unsp fracture of left lower leg, init for clos fx', '5/12/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (82, 'Keylex', 'Toxic effect of carbon disulfide, self-harm, subs', '12/24/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (83, 'Bamity', 'Puncture wound without foreign body of left breast', '7/28/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (84, 'Veribet', 'Supernumerary teeth', '7/13/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (85, 'Bytecard', 'Corrosion of third degree of right upper arm, subs encntr', '6/9/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (86, 'Fix San', 'Poisoning by unsp general anesthetics, assault, init encntr', '12/22/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (87, 'Trippledex', 'Non-prs chr ulc unsp prt of r low leg w fat layer exposed', '12/3/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (88, 'Temp', 'Insect bite (nonvenomous) of abdominal wall, subs encntr', '8/23/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (89, 'Fix San', 'Poisoning by rifampicins, accidental (unintentional), subs', '8/8/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (90, 'Konklab', 'Fx unsp metatarsal bone(s), unsp ft, 7thG', '12/18/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (91, 'Span', 'Corros 40-49% of body surface w 40-49% third degree corros', '8/23/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (92, 'Otcom', 'Nondisplaced Zone II fracture of sacrum, init for opn fx', '2/20/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (93, 'Tin', 'Displ unsp condyle fx low end unsp femr, 7thK', '12/3/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (94, 'Flexidy', 'Contact with goose', '4/18/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (95, 'Home Ing', 'Other contact with rat', '7/12/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (96, 'Zaam-Dox', 'Injury of unsp nerve at wrs/hnd lv of unsp arm, init', '7/2/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (97, 'Sub-Ex', 'Ulcerative (chronic) proctitis with fistula', '10/11/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (98, 'Subin', 'Unsp open wound of left eyelid and periocular area, subs', '1/5/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (99, 'Sonsing', 'Nondisp segmental fracture of shaft of ulna, unsp arm, init', '7/13/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (100, 'Otcom', 'Milt op involving explosion due to acc disch of own munit', '3/26/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (101, 'Transcof', 'Strain of flexor musc/fasc/tend thumb at forearm level', '9/7/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (102, 'Tres-Zap', 'Laceration without foreign body of right hand, sequela', '12/26/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (103, 'Flowdesk', 'Unsp injury of blood vessel of left index finger, init', '10/16/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (104, 'Fixflex', 'Strain of extensor musc/fasc/tend finger at wrs/hnd lv', '10/4/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (105, 'Asoka', 'Pain in hip', '5/17/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (106, 'Zontrax', 'Other fracture of right great toe', '10/4/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (107, 'Fix San', 'Poisoning by sulfonamides, accidental (unintentional), subs', '7/7/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (108, 'Bitwolf', 'Nondisp artic fx head of l femr, init for opn fx type 3A/B/C', '3/10/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (109, 'Trippledex', 'Drowning and submersion due to fall off unpowr wtrcrft', '2/1/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (110, 'Domainer', 'Nondisp spiral fx shaft of ulna, l arm, 7thC', '8/17/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (111, 'Aerified', 'Disp fx of olecran pro w/o intartic extn unsp ulna, 7thF', '9/4/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (112, 'Hatity', 'Pressure ulcer of left heel, stage 2', '5/1/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (113, 'Gembucket', 'Unsp disp fx of surg nk of r humer, subs for fx w routn heal', '1/16/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (114, 'Redhold', 'Salter-Harris Type II physeal fracture of r calcaneus, 7thK', '12/17/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (115, 'Opela', 'Corrosion of first degree of left knee', '9/17/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (116, 'Daltfresh', 'Corrosion of first degree of right shoulder', '3/10/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (117, 'Bigtax', 'Sexual abuse compl preg/chldbrth', '4/1/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (118, 'Quo Lux', 'Type 1 diab with mild nonp rtnop with macular edema, unsp', '8/6/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (119, 'Quo Lux', 'Unsp fracture of second lum vertebra, subs for fx w nonunion', '4/14/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (120, 'Toughjoyfax', 'Driver of hv veh injured in collision w hv veh in traf, init', '7/14/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (121, 'Fixflex', 'Corrosion of first degree of unspecified axilla, init encntr', '1/3/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (122, 'Asoka', 'Local-rel symptc epi w simp prt seiz,not ntrct, w/o stat epi', '5/18/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (123, 'Sub-Ex', 'Lobster-claw right hand', '12/23/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (124, 'Fixflex', 'Oth therapist or healthcare prov, perp of maltreat & neglect', '8/24/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (125, 'Ventosanzap', 'Intestine transplant infection', '9/5/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (126, 'Bamity', 'Osteitis deformans in neoplastic diseases, right ank/ft', '6/3/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (127, 'Stim', 'Nondisp bicondylar fx r tibia, 7thJ', '9/16/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (128, 'Bitchip', 'Unsp inj flxr musc/fasc/tend r lit fngr at wrs/hnd lv, sqla', '4/20/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (129, 'Toughjoyfax', 'Frostbite w tissue necros unsp knee and lower leg, sequela', '5/11/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (130, 'Quo Lux', 'Oth fracture of first thor vertebra, subs for fx w nonunion', '1/27/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (131, 'Regrant', 'Drown due to being washed overboard from unsp wtrcrft, subs', '11/20/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (132, 'Stim', 'Malignant neoplasm of right main bronchus', '4/11/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (133, 'Gembucket', 'Other helicopter accident injuring occupant', '3/25/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (134, 'Mat Lam Tam', 'Milt op w dest arcrft due to enmy fire/expls, civilian, init', '10/10/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (135, 'Cardguard', 'Poisoning by unsp systemic antibiotic, accidental', '9/30/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (136, 'Bitchip', 'Other specified disorders of teeth and supporting structures', '6/21/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (137, 'Prodder', 'Typhoid arthritis', '6/8/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (138, 'Wrapsafe', 'Displ intertroch fx r femr, 7thM', '1/7/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (139, 'Zoolab', 'Garden or yard of unsp non-institut residence as place', '5/29/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (140, 'Sonair', 'Abnormal head movements', '2/27/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (141, 'Y-find', 'Fracture of subcondylar process of left mandible, 7thK', '1/5/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (142, 'Overhold', 'Vaginismus not due to a substance or known physiol condition', '1/9/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (143, 'Gembucket', 'IsCompleted traumatic trnsphal amp of unsp finger, sequela', '7/12/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (144, 'Andalax', 'Sltr-haris Type I physl fx upr end l fibula, 7thP', '9/29/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (145, 'Pannier', 'Mech compl of nervous sys device, implant or graft, init', '3/4/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (146, 'Sonair', 'Oth injury due to oth accident on board sailboat, init', '12/6/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (147, 'Konklux', 'Postprocedural hypopituitarism', '3/12/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (148, 'Konklab', 'Unsp fx upper end of l humerus, subs for fx w delay heal', '4/8/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (149, 'Gembucket', 'Diagnostic and monitoring otorhino devices assoc w incdt', '1/30/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (150, 'Voyatouch', 'Fall on board watercraft', '8/15/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (151, 'Fintone', 'Exudative cysts of iris or anterior chamber, right eye', '7/7/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (152, 'Y-Solowarm', 'Burns of 80-89% of body surface w 40-49% third degree burns', '5/4/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (153, 'Tresom', 'Unsp intracap fx r femr, 7thE', '4/8/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (154, 'Kanlam', 'Major laceration of superior mesenteric artery', '10/10/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (155, 'Y-Solowarm', 'Strain of muscle and tendon of head, subsequent encounter', '2/8/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (156, 'Biodex', 'Coma scale, eyes open, spontaneous, EMR', '7/13/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (157, 'Duobam', 'Pauciarticular juvenile rheumatoid arthritis, unsp site', '2/27/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (158, 'Home Ing', 'Blister (nonthermal), right great toe, subsequent encounter', '5/27/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (159, 'Asoka', 'Strain of flexor musc/fasc/tend r thm at forarm lv, sequela', '1/21/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (160, 'Rank', 'Unsp car occ injured in clsn w pedl cyc nontraf, sequela', '7/17/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (161, 'Treeflex', 'Unstable burst fracture of fourth thoracic vertebra, sequela', '8/14/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (162, 'Matsoft', 'Carbuncle of right foot', '1/14/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (163, 'Matsoft', 'Moderate laceration of head of pancreas, initial encounter', '9/1/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (164, 'Temp', 'Unsp dislocation of right acromioclavicular joint, subs', '11/12/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (165, 'Sub-Ex', 'Hypervitaminosis D', '12/26/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (166, 'Solarbreeze', 'Band keratopathy, left eye', '6/3/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (167, 'Tin', 'Balanced rearrangements and structural markers, NEC', '5/14/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (168, 'Solarbreeze', 'Maternal care for hydrops fetalis, second trimester', '10/30/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (169, 'Solarbreeze', 'Contact with other commercial machinery, initial encounter', '7/23/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (170, 'Tresom', 'Cicatricial entropion of right upper eyelid', '2/14/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (171, 'Matsoft', 'Nondisp transverse fx shaft of unsp femr, 7thM', '12/7/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (172, 'Zamit', 'Disp fx of anterior column of unspecified acetabulum', '5/8/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (173, 'Cardify', 'Arthropathies in oth diseases classd elswhr, unsp site', '4/18/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (174, 'Zamit', 'Underdosing of mixed antiepileptics', '8/11/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (175, 'Zaam-Dox', 'Toxic effect of methanol, accidental (unintentional), subs', '9/5/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (176, 'Quo Lux', 'Other hemoglobinopathies', '1/8/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (177, 'Zontrax', 'Other subluxation of left ulnohumeral joint, init encntr', '5/13/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (178, 'Y-Solowarm', 'Corrosion of first degree of nose (septum), init encntr', '10/26/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (179, 'Voyatouch', 'Minor laceration of right internal jugular vein, subs encntr', '11/2/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (180, 'Keylex', 'Unspecified sprain of shoulder joint', '10/11/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (181, 'Bamity', 'Nondisp fx of neck of left talus, init for clos fx', '6/30/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (182, 'Sonsing', 'Diffuse cystic mastopathy of right breast', '10/2/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (183, 'Zoolab', 'Poisoning by anterior pituitary hormones, self-harm', '7/20/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (184, 'Quo Lux', 'Early congenital syphilitic pneumonia', '12/20/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (185, 'Zamit', 'Oth disorders of continuity of bone, pelvic region and thigh', '6/12/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (186, 'It', 'Glider (nonpowered) crash injuring occupant, subs encntr', '4/3/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (187, 'Fintone', 'Cardiac arrest following (induced) termination of pregnancy', '4/14/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (188, 'Quo Lux', 'Labor and delivery comp by oth evidence of fetal stress', '12/14/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (189, 'Ventosanzap', 'Other cholelithiasis', '4/8/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (190, 'Otcom', 'Unsp injury of deep palmar arch of left hand, init encntr', '6/24/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (191, 'Matsoft', 'Acute kidney failure', '3/24/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (192, 'Hatity', 'Ped on foot injured in collision w rail trn/veh in traf', '2/9/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (193, 'Stim', 'Subluxation of distal interphaln joint of r thm, sequela', '9/24/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (194, 'Veribet', 'Toxic effect of soaps', '5/14/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (195, 'Regrant', 'Displ commnt fx shaft of unsp femr, 7thQ', '5/18/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (196, 'Redhold', 'Other premature separation of placenta, second trimester', '4/22/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (197, 'Zaam-Dox', 'Toxic effect of arsenic and its compounds, self-harm, init', '3/7/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (198, 'Bigtax', 'Other peripheral vertigo, left ear', '9/21/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (199, 'Pannier', 'Congenital malformations of larynx', '3/1/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (200, 'Konklab', 'Disp fx of greater trochanter of right femur, init', '5/14/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (201, 'Transcof', 'Wedge comprsn fx first lum vertebra, init for opn fx', '5/11/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (202, 'Tampflex', 'Corros 90%/more of body surface w 30-39% third degree corros', '3/9/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (203, 'Veribet', 'Other chondrocalcinosis, unspecified knee', '2/1/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (204, 'Lotlux', 'Oth disrd of amniotic fluid and membrns, unsp tri, fetus 5', '3/17/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (205, 'Home Ing', 'Acquired stenosis of ext ear canal sec to inflam and infct', '3/8/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (206, 'Voltsillam', 'Subluxation of MTP joint of right great toe, subs', '9/5/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (207, 'Wrapsafe', 'Displ oblique fx shaft of l fibula, 7thC', '1/1/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (208, 'Ronstring', 'IsCompleted physeal arrest, right distal radius', '5/20/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (209, 'Asoka', 'Myositis ossificans traumatica, left hand', '3/15/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (210, 'Lotlux', 'Nondisp oblique fx shaft of humer, l arm, 7thD', '6/15/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (211, 'Konklux', 'Burn of unsp degree of multiple sites of ankle and foot', '5/31/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (212, 'Ventosanzap', 'Disp fx of med phalanx of left less toe(s), init for opn fx', '12/22/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (213, 'Cookley', 'Nondisplaced fracture of distal phalanx of left thumb', '3/12/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (214, 'Namfix', 'Unsp fracture of unsp acetabulum, subs for fx w nonunion', '4/12/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (215, 'Veribet', 'Unsp inj msl/tnd lng extn msl toe at ank/ft lev, r ft, init', '11/19/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (216, 'Prodder', 'Unsp fx low end r tibia, 7thF', '6/25/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (217, 'Stringtough', 'Puncture wound w foreign body oth prt neck, subs encntr', '2/4/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (218, 'Bitwolf', 'Lacerat abd wall w fb, unsp q w/o penet perit cav, init', '9/4/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (219, 'Greenlam', 'Primary open-angle glaucoma, unspecified eye, severe stage', '2/17/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (220, 'Hatity', 'Nondisp fx of ant pro of unsp calcaneus, 7thG', '5/19/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (221, 'Tempsoft', 'Strain of long flexor musc/fasc/tend l thm at wrs/hnd lv', '6/7/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (222, 'Alphazap', 'Exposure to oth smoke, fire and flames, subs encntr', '5/28/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (223, 'Zamit', 'Fuchs'' heterochromic cyclitis', '3/26/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (224, 'Konklab', 'Eumycetoma', '9/4/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (225, 'Mat Lam Tam', 'Toxic effect of paints and dyes, NEC, accidental, subs', '11/18/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (226, 'Pannier', 'Corrosion of second degree of right forearm, init encntr', '5/10/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (227, 'Keylex', 'Mech compl of internal fixation device of bones of limb', '11/8/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (228, 'Bigtax', 'Exposure of graft of urinary organ', '10/20/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (229, 'Tin', 'Dissem chorioretin inflammation of posterior pole, bilateral', '9/6/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (230, 'Fintone', 'Glaucomatous optic atrophy, right eye', '1/2/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (231, 'Andalax', 'Laceration of unsp blood vessel at wrs/hnd lv of left arm', '4/7/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (232, 'Toughjoyfax', 'Congenital vesico-uretero-renal reflux', '11/26/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (233, 'Zoolab', 'Oth fx shaft of left femur, init for opn fx type 3A/B/C', '1/15/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (234, 'Gembucket', 'Unspecified open wound of left upper arm', '3/3/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (235, 'Zaam-Dox', 'Lacrimal fistula right lacrimal passage', '6/30/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (236, 'Fixflex', 'Exposure to laser radiation, initial encounter', '5/16/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (237, 'Alpha', 'Unsp inj unsp blood vess at lower leg level, left leg, subs', '5/20/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (238, 'Mat Lam Tam', 'Yaws, unspecified', '5/2/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (239, 'It', 'Milt op involving unarmed hand to hand combat, milt, subs', '3/21/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (240, 'Domainer', 'Chlamydial infection of lower genitourinary tract', '8/30/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (241, 'Overhold', 'Poisoning by antithyroid drugs, undetermined, sequela', '4/10/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (242, 'Voltsillam', 'Superficial foreign body of unspecified hand', '7/12/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (243, 'Mat Lam Tam', 'Struck by alligator, initial encounter', '7/2/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (244, 'Flexidy', 'Dislocation of L2/L3 lumbar vertebra', '4/2/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (245, 'Lotstring', 'Nondisp fx of neck of 2nd MC bone, l hand, init for opn fx', '5/10/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (246, 'Treeflex', 'Unsp fx shaft of unsp rad, 7thR', '9/29/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (247, 'Konklux', 'Embolism and thrombosis of other and unsp parts of aorta', '11/26/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (248, 'Konklux', 'Prsn brd/alit from bus inj pick-up truck, pk-up/van, init', '3/25/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (249, 'Fixflex', 'Stress fracture, unspecified femur, sequela', '8/27/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (250, 'Trippledex', 'Displ seg fx shaft of ulna, r arm, 7thG', '5/25/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (251, 'Namfix', 'Unsp nondisp fx of 4th cervcal vert, subs for fx w nonunion', '4/14/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (252, 'Flexidy', 'Contusion of lip, sequela', '10/24/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (253, 'Zamit', 'Disp fx of acromial process, l shldr, subs for fx w nonunion', '9/9/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (254, 'Asoka', 'Corrosion of third degree of left forearm', '5/1/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (255, 'Namfix', 'Type III traum spondylolysis of sixth cervcal vert, 7thB', '4/30/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (256, 'Voltsillam', 'Primary open-angle glaucoma, unspecified eye, moderate stage', '7/30/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (257, 'Veribet', 'Maternal care for breech presentation, fetus 3', '11/21/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (258, 'Fix San', 'Mine or pit as the place of occurrence of the external cause', '12/24/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (259, 'Temp', 'Disp fx of medial phalanx of left index finger, sequela', '6/14/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (260, 'Tres-Zap', 'Fracture of pisiform', '8/15/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (261, 'Flowdesk', 'Poisoning by amphetamines, undetermined, sequela', '5/20/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (262, 'Toughjoyfax', 'Other chondrocalcinosis, left hand', '2/18/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (263, 'Bigtax', 'Pressure ulcer of unspecified hip, stage 3', '3/9/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (264, 'Fixflex', 'Pupillary abnormalities', '4/20/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (265, 'Tin', 'Osteochndrdys w defct of grth of tublr bones and spine, unsp', '3/1/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (266, 'Alphazap', 'Unsp open wound of oth finger w damage to nail, subs encntr', '4/1/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (267, 'Flexidy', 'Unsp fx the low end unsp rad, 7thM', '9/5/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (268, 'Hatity', 'Displ spiral fx shaft of humer, r arm, 7thP', '12/15/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (269, 'Rank', 'Fracture of unspecified skull and facial bones', '12/12/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (270, 'Bitwolf', 'Poisoning by antidiarrheal drugs, assault, initial encounter', '8/8/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (271, 'Rank', 'Coma scale, eyes open, to sound, unspecified time', '5/30/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (272, 'Alpha', 'Unspecified fracture of upper end of left humerus, sequela', '7/6/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (273, 'Tempsoft', 'Acute hematogenous osteomyelitis, unsp radius and ulna', '6/13/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (274, 'Hatity', 'Unspecified open wound of left elbow, subsequent encounter', '4/12/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (275, 'Transcof', 'Other superficial bite of oth part of neck, init encntr', '3/13/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (276, 'Viva', 'Unspecified injury of right Achilles tendon, subs encntr', '12/7/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (277, 'Cardguard', 'Nondisp fx of olecran pro w intartic extn unsp ulna, 7thD', '1/11/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (278, 'Viva', 'Spontaneous rupture of unspecified tendon', '9/26/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (279, 'Keylex', 'Encounter for fit/adjst of GI appliance and device', '12/26/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (280, 'Tresom', 'Displ bimalleol fx r low leg, 7thN', '7/5/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (281, 'Pannier', 'Injury of other nerves at hip and thigh level, right leg', '6/1/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (282, 'Biodex', 'Unspecified amblyopia, unspecified eye', '8/17/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (283, 'Alphazap', 'Other injury of unspecified kidney, initial encounter', '4/29/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (284, 'Keylex', 'Pnctr w foreign body of pharynx and cervical esophagus', '5/6/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (285, 'Sonair', 'Oth osteopor w current pathological fracture, unsp ank/ft', '11/5/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (286, 'Zathin', 'Malignant neoplasm of branchial cleft', '8/7/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (287, 'Zathin', 'Nondisp fx of coracoid process, unsp shoulder, init', '7/10/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (288, 'Tin', 'Abrasion, unspecified knee, initial encounter', '11/20/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (289, 'Quo Lux', 'Coma scale, eyes open, spontaneous, EMR', '1/3/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (290, 'Zamit', 'Disp fx of base of nk of unsp femr, 7thK', '9/20/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (291, 'Fintone', 'Oth specific arthropathies, NEC, unsp site', '1/4/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (292, 'Stronghold', 'Oth allergy status, oth than to drugs and biolg substances', '6/18/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (293, 'Duobam', 'Superficial foreign body of left elbow, sequela', '10/1/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (294, 'Regrant', 'Postural kyphosis, site unspecified', '4/13/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (295, 'Duobam', 'Burn of first degree of back of left hand, sequela', '11/13/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (296, 'Fix San', 'Oth complications following immunization, NEC', '4/5/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (297, 'Subin', 'Galeazzi''s fx r radius, subs for opn fx type I/2 w nonunion', '8/2/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (298, 'Bitchip', 'Inj flexor musc/fasc/tend left thumb at forearm level, subs', '2/1/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (299, 'Keylex', 'Crush inj unsp part(s) of unsp wrist, hand and fingers, init', '12/14/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (300, 'Namfix', 'Disp fx of proximal phalanx of unsp great toe, init', '3/16/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (301, 'Vagram', 'Underdosing of antiallergic and antiemetic drugs, init', '9/2/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (302, 'Redhold', 'Burn of unspecified degree of unspecified shoulder', '5/16/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (303, 'Bamity', 'Opioid dependence with intoxication, uncomplicated', '11/18/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (304, 'Home Ing', 'Driver of hv veh injured in clsn w statnry object in traf', '5/24/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (305, 'Otcom', 'Mantle cell lymphoma, intrapelvic lymph nodes', '1/8/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (306, 'Konklab', 'Underdosing of immunoglobulin, subsequent encounter', '9/2/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (307, 'Daltfresh', 'Flexion deformity, right shoulder', '12/11/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (308, 'Kanlam', 'Epidermolysis bullosa simplex', '6/8/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (309, 'Cardguard', 'Malignant neoplasm of central portion of right male breast', '6/3/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (310, 'Aerified', 'Other specified rheumatoid arthritis', '1/30/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (311, 'Overhold', 'Acquired partial absence of pancreas', '8/1/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (312, 'Vagram', 'Oth injuries of unsp wrist, hand and finger(s), init encntr', '4/7/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (313, 'Span', 'Skin changes due to chr expsr to nonionizing radiation, unsp', '12/25/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (314, 'Pannier', 'Sporotrichosis arthritis', '11/26/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (315, 'Andalax', 'Unspecified open wound of unspecified buttock, subs encntr', '6/7/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (316, 'Wrapsafe', 'Drown due to fall/jump fr crushed passenger ship, sequela', '5/10/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (317, 'Temp', 'Poisoning by oth vaccines and biolg substances, self-harm', '7/9/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (318, 'Tampflex', 'Corneal edema secondary to contact lens', '7/11/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (319, 'Flexidy', 'Unspecified fracture of shaft of fibula', '6/23/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (320, 'Greenlam', 'Unsp injury of unsp wrist, hand and finger(s), sequela', '1/1/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (321, 'Span', 'Lymphoblastic (diffuse) lymphoma, intra-abd lymph nodes', '4/3/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (322, 'Treeflex', 'Passenger of dune buggy injured in traffic accident, sequela', '4/9/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (323, 'Aerified', 'Sprain of ankle', '7/28/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (324, 'Sonsing', 'Disp fx of trapezoid, right wrist, subs for fx w malunion', '2/2/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (325, 'Voltsillam', 'Unsp fb in esophagus causing compression of trachea, subs', '10/14/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (326, 'Holdlamis', 'Accidental discharge of hunting rifle', '2/13/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (327, 'Trippledex', 'Fourth [trochlear] nerve palsy, bilateral', '3/27/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (328, 'Fix San', 'Sltr-haris Type III physl fx low end r tibia, 7thK', '5/5/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (329, 'Biodex', 'Inj to rider of nonrecr wtrcrft puld beh oth wtrcrft, sqla', '2/12/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (330, 'Zamit', 'Lacerat flexor musc/fasc/tend r idx fngr at forarm lv, subs', '7/29/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (331, 'Zathin', 'Sltr-haris Type I physl fx low end r tibia, 7thG', '10/9/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (332, 'Asoka', 'Nondisp fx of r tibial spine, subs for clos fx w malunion', '4/11/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (333, 'Bamity', 'Corrosion of right eye and adnexa, part unsp, init encntr', '1/25/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (334, 'Y-Solowarm', 'Laceration w foreign body of unsp part of neck, subs encntr', '1/15/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (335, 'It', 'Personal history of unspecified abuse in childhood', '5/3/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (336, 'Greenlam', 'Other specified arthritis, knee', '4/5/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (337, 'Treeflex', 'Crushing injury of right thigh, initial encounter', '12/10/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (338, 'Asoka', 'Family history of other specified eye disorder', '7/1/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (339, 'Alphazap', 'Unspecified internal derangement of left knee', '1/23/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (340, 'Alpha', 'Unsp open wound of left thumb w damage to nail, init encntr', '11/6/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (341, 'Trippledex', 'Mtrcy pasngr injured in clsn w nonmtr vehicle nontraf, subs', '9/23/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (342, 'Voltsillam', 'Varus deformity, not elsewhere classified, left elbow', '9/30/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (343, 'Namfix', 'Poisoning by cannabis (derivatives), assault, init encntr', '3/8/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (344, 'Zathin', 'Infective myositis, unspecified leg', '6/14/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (345, 'Sonsing', 'Assault by letter bomb, subsequent encounter', '4/26/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (346, 'Quo Lux', 'Transient synovitis, other site', '2/14/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (347, 'Aerified', 'Drowning and submersion due to sailboat sinking, sequela', '8/22/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (348, 'Voltsillam', 'Corrosion of second degree of chest wall, initial encounter', '5/27/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (349, 'Bitwolf', 'Nondisp spiral fx shaft of r femr, 7thE', '4/19/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (350, 'Stronghold', 'Biliary cyst', '6/16/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (351, 'Wrapsafe', 'Fatigue fx vertebra, lumbar region, subs for fx w routn heal', '6/19/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (352, 'Y-Solowarm', 'Occup of bus injured in clsn w rail trn/veh nontraf, subs', '1/7/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (353, 'Zathin', 'Nondisp transverse fx shaft of unsp rad, 7thN', '5/2/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (354, 'Job', 'Parapoxvirus infections', '4/9/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (355, 'Ronstring', 'Blister (nonthermal) of throat, sequela', '8/18/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (356, 'Prodder', 'Displ apophyseal fx l femr, 7thE', '6/13/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (357, 'Vagram', 'Displ intertroch fx r femr, 7thF', '5/3/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (358, 'Alphazap', 'Superficial frostbite of unspecified toe(s)', '11/27/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (359, 'Fintone', 'Oth place in school dormitory as place', '3/27/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (360, 'Mat Lam Tam', 'Hallucinogen dependence w oth hallucinogen-induced disorder', '7/29/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (361, 'Ventosanzap', 'Other psychoactive substance dependence, in remission', '8/31/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (362, 'Sonsing', 'Injury of deep peroneal nerve at ank/ft level, left leg', '4/8/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (363, 'Biodex', 'Impaired contrast sensitivity', '12/3/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (364, 'Kanlam', 'Unsp injury of greater saphenous vein at hip and thigh level', '1/29/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (365, 'Holdlamis', 'Insect bite (nonvenomous) of lip', '4/8/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (366, 'Aerified', 'Fx unsp prt of nk of unsp femr, 7thH', '8/15/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (367, 'Voyatouch', 'Lead-induced chronic gout, right ankle and foot, with tophus', '12/28/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (368, 'Matsoft', 'Gout due to renal impairment, elbow', '6/2/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (369, 'Alpha', 'Sprain of carpal joint of unspecified wrist, sequela', '9/10/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (370, 'Redhold', 'Postimmunization arthropathy, hip', '2/23/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (371, 'Ronstring', 'Cellulitis and abscess of mouth', '9/19/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (372, 'Zontrax', 'Underdosing of drug/meds/biol subst, init', '2/26/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (373, 'Transcof', 'Underdosing of pyrazolone derivatives, sequela', '11/2/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (374, 'Tampflex', 'Inj muscle, fascia and tendon of unsp hip, init encntr', '1/27/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (375, 'Daltfresh', 'Cocaine dependence', '1/19/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (376, 'Namfix', 'Oth abnormal findings on diagnostic imaging of cnsl', '11/29/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (377, 'Toughjoyfax', 'Pasngr in pk-up/van inj in nonclsn trnsp acc nontraf, subs', '7/21/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (378, 'Voltsillam', 'Fibrosis due to other internal prosth dev/grft, sequela', '9/18/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (379, 'Flowdesk', 'Nondisp fx of med condyle of unsp tibia, 7thM', '12/16/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (380, 'Transcof', 'Unsp fracture of fifth lumbar vertebra, init for opn fx', '1/14/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (381, 'Bitwolf', 'Strain of muscle and tendon of unsp wall of thorax, init', '2/4/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (382, 'Domainer', 'Burn of first degree of axilla', '7/14/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (383, 'Y-find', 'Poisoning by other narcotics, undetermined, init encntr', '10/9/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (384, 'Cardguard', 'Other specified cognitive deficit', '12/22/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (385, 'Zathin', 'Laceration with foreign body of oral cavity, subs encntr', '7/8/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (386, 'Mat Lam Tam', 'Aseptic peritonitis due to forn sub acc left dur proc, sqla', '2/28/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (387, 'Y-Solowarm', 'Melanocytic nevi of scalp and neck', '6/4/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (388, 'Latlux', 'Rheumatoid polyneurop w rheumatoid arthritis of unsp knee', '3/31/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (389, 'Aerified', 'Age-related osteopor w current pathological fracture, ank/ft', '6/25/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (390, 'Bytecard', 'Nondisp subtrochnt fx unsp femr, subs for clos fx w nonunion', '12/17/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (391, 'Veribet', 'Oth meniscus derang, post horn of medial meniscus, unsp knee', '5/25/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (392, 'Fintone', 'Cerebral arteritis, not elsewhere classified', '5/7/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (393, 'It', 'Idiopathic chronic gout, unspecified hip, without tophus', '12/4/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (394, 'Konklab', 'Age-rel osteopor w crnt path fx, r humer, 7thD', '6/25/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (395, 'Solarbreeze', 'Milt op w chem weapons and oth unconvtl warfare, civ, init', '2/23/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (396, 'Zontrax', 'Fusion of spine, lumbosacral region', '6/19/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (397, 'Alpha', 'Unspecified open wound of unspecified shoulder, subs encntr', '7/11/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (398, 'Otcom', 'Assault by fertilizer bomb', '10/30/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (399, 'Sonair', 'Diab with prolif diabetic rtnop without macular edema, r eye', '3/19/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (400, 'Voltsillam', 'Eclampsia, unspecified as to time period', '4/3/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (401, 'Quo Lux', 'Unsp injury of less saphenous at lower leg level, unsp leg', '5/10/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (402, 'Transcof', 'Exostosis of right orbit', '2/25/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (403, 'Subin', 'Unsp injury of radial artery at forarm lv, left arm, init', '4/15/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (404, 'Home Ing', 'Oth osteopor w crnt path fx, l hand, 7thG', '6/4/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (405, 'Lotstring', 'Dislocation of T6/T7 thoracic vertebra', '6/5/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (406, 'Redhold', 'Contusion of thorax, unspecified, initial encounter', '7/23/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (407, 'Voltsillam', 'Unsp physeal fracture of upper end of right femur, sequela', '9/24/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (408, 'Gembucket', 'Diab with prolif diabetic rtnop with trctn dtch n-mcla, bi', '8/7/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (409, 'Greenlam', 'Puncture wound w foreign body of right shoulder, subs encntr', '9/25/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (410, 'Greenlam', 'Sezary disease, unspecified site', '11/8/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (411, 'Pannier', 'Pathological dislocation of unsp hip, NEC', '11/3/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (412, 'Latlux', 'Maternal care for excess fetal growth, third tri, fetus 4', '6/26/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (413, 'Mat Lam Tam', 'Other specified congenital malformations of integument', '5/4/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (414, 'Home Ing', 'Crushing injury of unspecified hand, subsequent encounter', '1/11/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (415, 'Voyatouch', 'Adverse effect of unspecified general anesthetics, sequela', '7/7/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (416, 'Wrapsafe', 'Displ spiral fx shaft of l femr, 7thQ', '9/27/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (417, 'Y-find', 'Ped on sktbrd injured in collision w pedl cyc nontraf, init', '4/30/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (418, 'Matsoft', 'Goniosynechiae, bilateral', '3/16/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (419, 'Kanlam', 'Congenital compression facies', '11/29/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (420, 'Prodder', 'Oth injury of femoral artery, right leg, subs encntr', '3/4/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (421, 'Span', 'Unspecified foreign body in trachea causing other injury', '2/10/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (422, 'Bytecard', 'Nondisp fx of body of scapula, l shldr, 7thG', '5/14/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (423, 'Lotstring', 'Pleurodynia', '12/3/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (424, 'Tin', 'Dry beriberi', '5/10/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (425, 'Temp', 'Disp fx of second metatarsal bone, l foot, init for opn fx', '7/27/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (426, 'Zaam-Dox', 'Nondisp fx of olecran pro w/o intartic extn unsp ulna, 7thP', '1/28/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (427, 'Tempsoft', 'Breakdown (mechanical) of unsp vascular grafts, sequela', '2/13/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (428, 'Fintone', 'Dir infct of unsp elbow in infec/parastc dis classd elswhr', '11/12/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (429, 'Bitwolf', 'Contus/lac l cereb w LOC w dth d/t brain inj bf consc, init', '5/20/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (430, 'Sub-Ex', 'Leakage of biological heart valve graft', '6/5/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (431, 'Tresom', 'Intraoperative cardiac arrest during cardiac surgery', '7/7/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (432, 'Sub-Ex', 'Other specified inflammatory spondylopathies, lumbar region', '4/11/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (433, 'Vagram', 'Alcohol use, unspecified with intoxication, uncomplicated', '7/24/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (434, 'Stronghold', 'Crushing injury of unspecified lesser toe(s), sequela', '11/3/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (435, 'Zaam-Dox', 'Heart and lungs transplant status', '10/9/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (436, 'Cardguard', 'Infect/inflm reaction due to periton dialysis catheter, init', '4/13/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (437, 'Ventosanzap', 'Failed or difficult intubation for anesth during pregnancy', '6/14/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (438, 'Zamit', 'Inj intercostal blood vessels, unsp side, subs encntr', '4/7/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (439, 'Biodex', 'Other specified injury of deep palmar arch of right hand', '6/24/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (440, 'Opela', 'Pauciarticular juvenile rheumatoid arthritis, left wrist', '6/24/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (441, 'Cookley', 'Retained (old) magnetic fb in ant chamber, unsp eye', '3/5/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (442, 'Sub-Ex', 'Gammaherpesviral mononucleosis without complication', '1/27/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (443, 'Span', 'Toxoplasma tubulo-interstitial nephropathy', '2/20/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (444, 'Pannier', 'Oth fx upr end unsp ulna, 7thJ', '8/29/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (445, 'Fintone', 'Erosion of teeth', '4/9/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (446, 'Temp', 'And unsp agents primarily affecting the cardiovascular sys', '7/17/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (447, 'Stringtough', 'Staphylococcal arthritis, hip', '5/22/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (448, 'Biodex', 'Personal history of (healed) traumatic fracture', '12/4/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (449, 'Tampflex', 'Ant subcapsular polar infantile and juvenile cataract, r eye', '11/1/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (450, 'Sub-Ex', 'Puncture wound with foreign body, right hip, init encntr', '3/17/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (451, 'Opela', 'Disp fx of 1st metatarsal bone, r ft, subs for fx w malunion', '6/16/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (452, 'Kanlam', 'Pathological fracture, unsp hand, init encntr for fracture', '6/1/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (453, 'Gembucket', 'Perf due to fb acc left in body fol infusn/transfusn, subs', '7/12/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (454, 'Tin', 'Pasngr in 3-whl mv inj in clsn w 2/3-whl mv in traf, init', '9/14/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (455, 'Vagram', 'Poisoning by unspecified narcotics, intentional self-harm', '6/22/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (456, 'Bigtax', 'Acute bronchiolitis, unspecified', '7/6/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (457, 'Holdlamis', 'Maternal care for oth conditions predom related to pregnancy', '11/15/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (458, 'Duobam', 'Vogt-Koyanagi syndrome, left eye', '8/30/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (459, 'Kanlam', 'Nondisp fx of coronoid pro of r ulna, 7thP', '7/16/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (460, 'Temp', 'Insect bite (nonvenomous) of left back wall of thorax, subs', '11/19/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (461, 'Bigtax', 'Congenital torsion of penis', '1/4/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (462, 'Fixflex', 'Drug/chem diabetes w unsp diabetic rtnop w macular edema', '4/8/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (463, 'Y-find', 'Nondisp fx of base of fifth MC bone, right hand, init', '5/24/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (464, 'Fixflex', 'Corrosion of third degree of right thumb (nail)', '2/16/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (465, 'Job', 'Sltr-haris Type II physl fx low end r femr, 7thD', '10/31/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (466, 'Tempsoft', 'Blister (nonthermal) of throat', '4/1/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (467, 'Latlux', 'Drug-induced chronic gout, left hip', '8/4/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (468, 'Bitwolf', 'Passenger in hv veh injured in clsn w oth mv nontraf, init', '6/17/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (469, 'Treeflex', 'Nondisp bimalleol fx l low leg, 7thJ', '1/22/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (470, 'Sub-Ex', 'Blister (nonthermal) of throat, sequela', '10/19/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (471, 'Y-Solowarm', 'Inj l int carotid, intcr w LOC >24 hr w ret consc lev, init', '10/10/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (472, 'Stringtough', 'Lipoprotein deficiency', '3/10/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (473, 'Bitchip', 'Terrorism involving nuclear weapons', '6/8/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (474, 'Hatity', 'Path fracture in oth disease, l ulna, subs for fx w malunion', '1/13/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (475, 'Bigtax', 'Late congenital syphilitic interstitial keratitis', '9/11/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (476, 'Tampflex', 'Gas gangrene', '8/1/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (477, 'Span', 'Laceration with foreign body of unsp upper arm, sequela', '11/27/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (478, 'Voltsillam', 'Unsp inj msl/tnd lng flxr msl toe at ank/ft lev, r ft, subs', '12/25/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (479, 'Prodder', 'IsCompleted traumatic transphalangeal amputation of r idx fngr', '1/8/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (480, 'Tampflex', 'Laceration of oth blood vessels at lower leg level, left leg', '7/3/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (481, 'Matsoft', 'Pnctr w fb of abd wall, periumb rgn w penet perit cav, init', '10/19/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (482, 'Y-find', 'Postural kyphosis, thoracolumbar region', '9/9/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (483, 'Holdlamis', 'Acute post multifoc placoid pigment epitheliopathy, unsp eye', '4/23/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (484, 'Job', 'Perf due to fb acc left in body fol inject or immuniz, subs', '7/6/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (485, 'Namfix', 'Oth fx upr & low end r fibula, subs for clos fx w delay heal', '4/7/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (486, 'Tampflex', 'Displaced oblique fracture of shaft of left tibia, sequela', '10/20/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (487, 'Pannier', 'Leukemia, unspecified, in remission', '10/19/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (488, 'Ventosanzap', 'Other calcification of muscle, unspecified ankle and foot', '4/6/2020', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (489, 'Lotstring', 'Medial dislocation of proximal end of tibia, unsp knee, subs', '4/18/2023', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (490, 'Zaam-Dox', 'Injury of facial nerve, right side', '10/14/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (491, 'Opela', 'Sltr-haris Type III physeal fx lower end radius, left arm', '7/11/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (492, 'Lotstring', 'Nondisp transcondy fx l humerus, subs for fx w malunion', '5/22/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (493, 'Matsoft', 'Displacement of electronic bone stimulator', '12/4/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (494, 'Hatity', 'Stress fracture, left toe(s), initial encounter for fracture', '10/31/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (495, 'Span', 'Malignant neoplasm of axillary tail of right male breast', '3/14/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (496, 'Alpha', 'Contusion of unsp great toe without damage to nail, sequela', '9/18/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (497, 'Rank', 'Poisn by anticoag antag, vit K and oth coag, acc, sequela', '1/26/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (498, 'Home Ing', 'Unspecified injury of left carotid artery, initial encounter', '7/10/2022', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (499, 'Stronghold', 'Burn of second degree of left wrist, sequela', '12/8/2021', 0);
insert into Tasks (id, title, Description, DueDate, IsCompleted) values (500, 'Bamity', 'Unspecified dislocation of left index finger, sequela', '4/8/2021', 0);
SET IDENTITY_INSERT Tasks OFF
